language: python
python:
  - "3.7"

install:
  - pip install -r requirements.txt

jobs:
  include:
    - stage: lint
      script: python3 -m 'flake8' *.py statipie tests util
    - stage: test
      script: python3 -m unittest discover
